import QueryAnswearBox from '@/components/ui/custom/queryAnswerBox';
import { TQAbox } from '@/types';

const FaqSection = () => {
    const faq: TQAbox = [
        {
            question: 'What is LeadLoom?',
            answer: 'LeadLoom is the collection of free to play games that rewards🏆 you for playing🕹️. You can play games, complete tasks and earn rewards.🏅',
        },
        {
            question: 'When will I get my reward paid?',
            answer: 'When the challenge status changes to confirmed',
        },
        {
          question: 'When will the status change from accepted to confirmed?',
          answer: 'Once the advertiser confirms acceptance of the challenge, it takes 30-90 days depending on the program (usually about 35 days. Remember that all program conditions and leadloom regulations must be met in order for the advertiser to accept your challenge/lead.',
        },
        {
          question: 'What is LeadLoom lead?',
          answer: 'LeadLoom lead is a completed challenge bt you from program list.',
        },
        {
          question:"What is LeadLoom pending lead?",
          answer:"LeadLoom lead is a completed challenge that is generated by you and is not accepted yet by the advertiser."
        },
        {
          question:"What is LeadLoom accepted lead?",
          answer:"LeadLoom lead is a completed challenge that is accepted by the advertiser. Once the advertiser accepts your lead, it will be moved to the confirmed section. And the lead is ready to be paid."
        },
        {
          question:"What are the payment thresholds?",
          answer:"The minimum payment threshold depends on the country and currency. You can check the latest paid-out thresholds in your dashboard. You can request payment once you reach the minimum payment threshold."
        },
        {
          question:"Why has my lead been rejected?",
          answer:<>there are several possibilities
          <ul className="list-inside list-disc">
            <li>You haven't met all the challenge requirements
              <br />
              e.g.you didn't confirm your email, you didn't complete all the missions
            </li>
            <li>
            You already had other cookies from the challenge but not related to leadloom app
            </li>
            <li>You cheated, you created multiple accounts on one PC or the same IP network</li>
            <li>You had adblock turned on, which cleared the link's tracking parameters. In such a case, it is not possible to complete the challenge</li>
          </ul>
          </>
        }
    ];
    return (
        <section className="mb-4  mt-4 flex flex-col gap-4 ">
            <QueryAnswearBox qas={faq} />
        </section>
    );
};

export default FaqSection;
